In [2]:
from mxnet import np, npx
npx.set_np()

# scalar

In [6]:
x = np.array(3.0)
y = np.array(2.0)

In [7]:
x+y, x*y, x/y, x**y

(array(5.), array(6.), array(1.5), array(9.))

#  vector 
#vector, you can think a list of simple values

In [13]:
x = np.arange(10)

In [14]:
x[3]

array(3.)

In [15]:
len(x)

10

In [16]:
x.shape

(10,)

# matrices

In [18]:
A = np.arange(20).reshape(5,-1)

In [19]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [20]:
B = A.T

In [21]:
B

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [22]:
# symmetric matrix A = A.T

In [23]:
c = np.array([[1,2,3],[2,0,4],[3,4,5]])
c

array([[1., 2., 3.],
       [2., 0., 4.],
       [3., 4., 5.]])

# Tensor

In [25]:
X = np.arange(24).reshape(2,3,4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [27]:
A = np.arange(20).reshape(5,4)
B = A.copy()
A, A+B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]))

In [28]:
A*B

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]])

In [29]:
# Multiplying or adding tensor with scalar does not change the shape of the tensor

In [30]:
a = 2
x = np.arange(24).reshape(2,3,4)


In [31]:
a*x

array([[[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]],

       [[24., 26., 28., 30.],
        [32., 34., 36., 38.],
        [40., 42., 44., 46.]]])

In [32]:
a+x

array([[[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.]],

       [[14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.]]])

In [33]:
a-x

array([[[  2.,   1.,   0.,  -1.],
        [ -2.,  -3.,  -4.,  -5.],
        [ -6.,  -7.,  -8.,  -9.]],

       [[-10., -11., -12., -13.],
        [-14., -15., -16., -17.],
        [-18., -19., -20., -21.]]])

In [34]:
x/a

array([[[ 0. ,  0.5,  1. ,  1.5],
        [ 2. ,  2.5,  3. ,  3.5],
        [ 4. ,  4.5,  5. ,  5.5]],

       [[ 6. ,  6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5]]])

# Reduction
To calculate the some of the elements of tensor

In [35]:
x = np.arange(5)
x, x.sum()

(array([0., 1., 2., 3., 4.]), array(10.))

In [36]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [37]:
A.shape, A.sum()

((5, 4), array(190.))

In [38]:
A_sum_axis_0 = A.sum(axis=0)
A_sum_axis_0, A_sum_axis_0.shape

(array([40., 45., 50., 55.]), (4,))

In [39]:
A_sum_axis_1 = A.sum(axis=1)
A_sum_axis_1, A_sum_axis_1.shape

(array([ 6., 22., 38., 54., 70.]), (5,))

In [40]:
A.sum(axis=[0,1])

array(190.)

In [41]:
A.mean(), A.sum()/A.size

(array(9.5), array(9.5))

In [43]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

# Non reduction sum

In [44]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])

In [45]:
A/sum_A

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]])

In [46]:
A.cumsum(axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]])

# Dot product

In [50]:
y = np.ones(5)

In [52]:
x, y, np.dot(x,y)

(array([0., 1., 2., 3., 4.]), array([1., 1., 1., 1., 1.]), array(10.))

In [53]:
np.sum(x*y)

array(10.)

# Matrix vector product

In [54]:
A.shape # A is a matrix of shape [5,4]

(5, 4)

In [58]:
x = np.arange(4) # x is a vector of 4

In [59]:
x

array([0., 1., 2., 3.])

In [60]:
np.dot(A,x)

array([ 14.,  38.,  62.,  86., 110.])

In [61]:
pro = np.dot(A,x)

In [62]:
pro.shape

(5,)

# Matrix to matrix multiplication

In [63]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [64]:
B = np.ones((4,3))

In [65]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
prod = np.dot(A,B)

In [67]:
prod

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

In [68]:
prod.shape

(5, 3)

# Norms

In [70]:
u = np.array([3, -4])
np.linalg.norm(u)


array(5.)

In [71]:
np.abs(u).sum()

array(7.)

In [72]:
np.linalg.norm(np.ones((4,9)))

array(6.)