In [2]:
from mxnet import np, npx
npx.set_np()

In [3]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

(12,)

In [5]:
x.size  #multiplication of the shape

12

In [6]:
x = x.reshape(3,4)

In [7]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [8]:
x.size

12

In [21]:
y = x.reshape(-1,3)

In [22]:
y

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
z = x.reshape(2,-1)

In [26]:
z

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [29]:
#empty matrix
emt = np.empty((3,4))

In [30]:
emt

array([[2.5225907e-18, 6.4824512e-10, 1.0356199e-11, 3.0881433e-09],
       [1.0503973e-05, 4.2106964e-11, 1.0781197e-08, 2.9570567e-18],
       [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27]])

In [31]:
#zero tensor
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
#once
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
# create a tensor which contain element with gaussian distributed values
np.random.normal(0, 1, size=(3,4))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 ,  0.4838046 ],
       [ 1.0434405 ,  0.29956347,  1.1839255 ,  0.15302546],
       [ 1.8917114 , -1.1688148 , -1.2347414 ,  1.5580711 ]])

In [34]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [35]:
# operations


In [36]:
x = np.array([1,3,4,5])
y = np.array([2,4,1,6])

In [37]:
x+y , x-y, x*y, x/y, x**y

(array([ 3.,  7.,  5., 11.]),
 array([-1., -1.,  3., -1.]),
 array([ 2., 12.,  4., 30.]),
 array([0.5      , 0.75     , 4.       , 0.8333333]),
 array([1.0000e+00, 8.1000e+01, 4.0000e+00, 1.5625e+04]))

In [38]:
np.exp(x)

array([  2.7182817,  20.085537 ,  54.59815  , 148.41316  ])

In [42]:
x = np.arange(12).reshape(-1,4)
y = np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

In [43]:
concat_row = np.concatenate([x,y], axis=0)

In [44]:
concat_row

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]])

In [45]:
concat_col = np.concatenate([x,y], axis=1)

In [46]:
concat_col

array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [47]:
x == y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
#summing all element of the tensor
x.sum()

array(66.)

In [50]:
#broadcasting mechanism
# To perform elementwise operation with different size tensors


In [51]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)

In [52]:
a, b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]))

In [53]:
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

In [54]:
a-b

array([[ 0., -1.],
       [ 1.,  0.],
       [ 2.,  1.]])

In [55]:
a*b

array([[0., 0.],
       [0., 1.],
       [0., 2.]])

In [56]:
# Indexing and slicing

In [63]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
x[-1]

array([ 8.,  9., 10., 11.])

In [66]:
x[1:3]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [67]:
x[2,3]

array(11.)

In [68]:
x[1,2] = 9

In [69]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [70]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [71]:
y

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [81]:
#saving memory

In [72]:
before = id(y)

In [73]:
before

140557839067008

In [74]:
y = x+y

In [76]:
id(y) == before

False

In [79]:
z = np.zeros_like(y)
print('id(z):', id(z))
z[:] = x+y
print('id(z):', id(z))

id(z): 140557839205952
id(z): 140557839205952


In [80]:
before = id(x)
x+= y
id(x) == before

True

In [82]:
#converting other python object

In [83]:
a = x.asnumpy()
b = np.array(a)
type(a), type(b)

(numpy.ndarray, mxnet.numpy.ndarray)

In [84]:
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

In [85]:
x 

array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 21., 18.],
       [20., 21., 22., 23.]])

In [86]:
y

array([[ 2.,  2.,  6.,  6.],
       [ 5.,  7., 12., 11.],
       [12., 12., 12., 12.]])

In [87]:
x > y

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
x < y

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])